development:
  min_messages: WARNING
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  encoding: unicode
  database: sample_app_development
  pool: 5
  username: raaid
  password: "159"

test:
  min_messages: WARNING
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: raaid
  password: "159"

production:
  min_messages: WARNING
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  encoding: unicode
  database: sample_app_production
  pool: 5
  username: raaid
  password: "159"
